# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' rcpp_get_sp_dists_par
#'
#' @noRd
rcpp_get_sp_dists_par <- function(graph, vert_map_in, fromi, d_threshold, heap_type) {
    .Call(`_moveability_rcpp_get_sp_dists_par`, graph, vert_map_in, fromi, d_threshold, heap_type)
}

#' rcpp_get_sp_dists
#'
#' @noRd
rcpp_get_sp_dists <- function(graph, vert_map_in, fromi, d_threshold, heap_type) {
    .Call(`_moveability_rcpp_get_sp_dists`, graph, vert_map_in, fromi, d_threshold, heap_type)
}

#' rcpp_reverse_index
#'
#' Return an index of rows, j > i, for which 
#' [from(j) == to (i), to(j) == from (i)]. These are edges duplicated in
#' reverse which can then be removed.
#'
#' @param df Rcpp::DataFrame with 2 columns named "from" and "to"
#'
#' @return 0-indexed Rcpp::NumericVector index into graph of nearest points
#'
#' @noRd
rcpp_reverse_index <- function(df) {
    .Call(`_moveability_rcpp_reverse_index`, df)
}

