# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' rcpp_get_sp_dists_par
#'
#' @noRd
rcpp_get_sp_dists_par <- function(graph, vert_map_in, fromi, d_threshold, heap_type) {
    .Call(`_moveability_rcpp_get_sp_dists_par`, graph, vert_map_in, fromi, d_threshold, heap_type)
}

#' rcpp_sf_as_network
#'
#' Return OSM data from Simple Features format input
#'
#' @param sf_lines An sf collection of LINESTRING objects
#' @param pr Rcpp::DataFrame containing the weighting profile
#'
#' @return Rcpp::List objects of OSM data
#'
#' @noRd
rcpp_sf_as_network <- function(sf_lines, pr) {
    .Call(`_moveability_rcpp_sf_as_network`, sf_lines, pr)
}

#' rcpp_points_index_par
#'
#' Get index of nearest vertices to list of points
#'
#' @param graph Rcpp::DataFrame containing the graph
#' @param pts Rcpp::DataFrame containing the routing points
#'
#' @return 0-indexed Rcpp::NumericVector index into graph of nearest points
#'
#' @noRd
rcpp_points_index_par <- function(xy, pts) {
    .Call(`_moveability_rcpp_points_index_par`, xy, pts)
}

#' rcpp_points_index
#'
#' Get index of nearest vertices to list of points
#'
#' @param graph Rcpp::DataFrame containing the graph
#' @param pts Rcpp::DataFrame containing the routing points
#'
#' @return 0-indexed Rcpp::NumericVector index into graph of nearest points
#'
#' @noRd
rcpp_points_index <- function(xy, pts) {
    .Call(`_moveability_rcpp_points_index`, xy, pts)
}

#' rcpp_reverse_index
#'
#' Return an index of rows, j > i, for which 
#' [from(j) == to (i), to(j) == from (i)]. These are edges duplicated in
#' reverse which can then be removed.
#'
#' @param df Rcpp::DataFrame with 2 columns named "from" and "to"
#'
#' @return 0-indexed Rcpp::NumericVector index into graph of nearest points
#'
#' @noRd
rcpp_reverse_index <- function(df) {
    .Call(`_moveability_rcpp_reverse_index`, df)
}

